sudo: required

language: generic

git:
  depth: false

dist:
  xenial

services:
  - docker

before_install:
  - docker pull moussavdb/build-nodejs

script:
  - DOCKER_COMMAND='yarn install && ng build --prod'
  - docker run -v $PWD:/src -w /src moussavdb/build-nodejs "$DOCKER_COMMAND"
