image: node:10.3.0

pipelines:
  default:
    - step:
        name: Build artifact
        script:
          - npm install -g yarnpkg
          - npm install -g @angular/cli
          - yarn install
          - ng build --prod
          - tar zcvf repo-web_${BITBUCKET_BUILD_NUMBER}.tar.gz dist/
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/yildiz-engine-team/repo-web/downloads" --form files=@"repo-web_${BITBUCKET_BUILD_NUMBER}.tar.gz"
