image: node:10.3.0

pipelines:
  default:
    - step:
        script:
          - npm install -g yarnpkg
          - npm install -g @angular/cli
          - yarn install
          - ng build --prod
          - tar cvf repo-web.tar dist
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"repo-web.tar"
